sudo: required
dist: trusty
language: python

matrix:
    include:
        - python: 3.5
          env:
            - PYFLAKES=1
            - PEP8=1
          script:
            - pylint -rn qiskit test
            - pycodestyle --max-line-length=100 qiskit test
        - python: 3.6
          env:
        - python: 3.6
          env: CC=clang CXX=clang++
        - python: 3.6
          env: OPENMP=1
        - os: osx
          osx_image: xcode9.2
          language: generic
          env:
            - TRAVIS_PYTHON_VERSION=3.6

# command to install dependencies
install:
  - echo $TRAVIS_OS_NAME
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then  
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      else
        brew install wget;
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
    fi
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    #- conda update -q conda
    - conda info -a
    - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
    - source activate test-environment
    - if [[ "${OPENMP}" == "1" ]]; then
          conda install nomkl numpy scipy cython;
        else
          conda install mkl numpy scipy cython;
      fi
    # Finally, build Cython modules.
    - python setup.py build_ext --inplace

# command to run tests
script: 
    - python -m unittest discover -s test -v