sudo: false
dist: trusty
language: python

matrix:  
  include:
      - os: linux
        addons:
          apt:
            sources:
              - ubuntu-toolchain-r-test
            packages:
              - g++-5  
      - python: 3.5
          env:
            - PYFLAKES=1
            - PEP8=1
          script:
            - pylint -rn qiskit test
            - pycodestyle --max-line-length=100 qiskit test
      - python: 3.6
          env:
      - python: 3.6
          env: CC=clang CXX=clang++
      - python: 3.6
          env: OPENBLAS=1
      - os: osx
          osx_image: xcode9.2
          language: generic
          

# command to install dependencies
install:
  - echo $TRAVIS_OS_NAME 
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  #- conda update -q conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment
  - if [[ "${OPENBLAS}" == "1" ]]; then
        conda install nomkl numpy scipy cython sympy;
      else
        conda install mkl numpy scipy cython sympy;
    fi
  - pip install IBMQuantumExperience
  # Finally, build Cython modules.
  - python setup.py build_ext --inplace

# command to run tests
script: 
    - python -m unittest discover -s test -v